### ISSUE TITLE
Use Open Government licence?

### ISSUE THREAD

**Issue by michaeldfallen** [alphagov/govuk_template#143]
It's not really designed for code but should we be using the https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/?

Currently this is published with the MIT licence which is very similar so I don't think there's any change in permissions between the two.

**Comment by bradleywright** [comment]
We've left our position on this in a [comment on a blog article](https://gds.blog.gov.uk/2012/10/12/coding-in-the-open/#comment-2388) (quoted here for posterity):

> MIT felt more appropriate [than the open government licence] as a license for code as it’s designed for that purpose. It’s also more widely recognised in the software world and so makes it easier for other developers to make decisions about whether or not to use our code.

**Comment by michaeldfallen** [comment]
Fair enough, makes a lot of sense. Is that the suggested approach for other projects by government departments? Reason I'm asking is we are about to publish the template as a python `egg` ([python-govuk-template](https://github.com/LandRegistry/python-govuk-template)) and I wasn't certain what licence to use.

**Comment by tijmenb** [comment]
Here's some more info on our use of MIT: https://gds-way.cloudapps.digital/manuals/licensing.html
