### ISSUE TITLE
Publish the Jinja version to a repo for use in NPM

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk_template#181]
We're moving https://github.com/alphagov/govuk_prototype_kit to use Nunjucks, which is a JavaScript implementation of Jinja.

It would be very useful to get a version of the template from NPM in the same way we currently do with Mustache.

**Comment by timpaul** [comment]
:+1:

**Comment by gemmaleigh** [comment]
#198 fixes this.

**Comment by joelanman** [comment]
Woop!
