### ISSUE TITLE
Crest not loaded in Chrome/Safari

### ISSUE THREAD

**Issue by antimega** [alphagov/govuk_template#182]
The line
background-image: image-url("images/govuk-crest.png"); 
in govuk_template/source/assets/stylesheets/_header.scss
causes a warning and the image to not to be displayed.

Changing to 
background-image: url("images/govuk-crest.png"); 
works but I haven't tested it across more browsers.

**Comment by bradwright** [comment]
`image-url` is part of `rails-sass` - what SCSS compiler are you using to generate the file?

**Comment by gemmaleigh** [comment]
Are you using the front end toolkit's URL helpers?
https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/_url-helpers.scss

I think you may need to define `$path` for `image-url` to work.

// Path to assets for use if file-url() is not already defined
@if ($path == false) {
  $path: "/public/images/";
}

The `file-url` helper will by default output an `image-url` to
be used with Compass or Rails Asset Pipeline, if you want to use a static path
then set the `$path` variable to point to the public location of the toolkit
image assets.

**Comment by dsingleton** [comment]
@antimega are you still having this issue and if so, could you share the code this was happening in?

**Comment by nickcolley** [comment]
@antimega closing this out, if you're still running into this feel free to reopen with some steps to reproduce 👍
