### ISSUE TITLE
For consideration: add new insertion block immediately after DOCTYPE

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_template#199]
We use GOV.UK template in the prototype kit. I'd like to place a message at the top of the page that is visible in the markup when users open the inspector. I could see this being useful to other services too.

Something like this:
![screen shot 2016-02-15 at 13 37 15](https://cloud.githubusercontent.com/assets/2204224/13050338/93e415b8-d3ea-11e5-9c94-2275e0bfc5e3.png)

To me, the obvious place is immediately after the doctype declaration - I'd like to suggest a new insertion point be added:
`{% block after_doctype %}{% endblock %}`

Does this seem sensible?

**Comment by fofr** [comment]
Would something large and garish in `head` also work? Perhaps like The Guardian does:

![screen shot 2016-02-16 at 10 46 35](https://cloud.githubusercontent.com/assets/319055/13074127/9a837084-d49a-11e5-81f7-4c30d4d6b66d.png)


You might want to include something along the lines of:
`console.log("Do not use this kit for production services");`

**Comment by dsingleton** [comment]
:+1: to the idea.

**Comment by edwardhorsford** [comment]
Looks like Chrome auto-collapses head - hence putting it higher.

I don't know if there are any performance considerations to putting something there. Don't some of the meta tags need to come within x first bytes?

**Comment by gemmaleigh** [comment]
`<meta charset="utf-8">`[must be inside the `<head>` element and within the 512 first bytes of the page](https://developer.mozilla.org/en/docs/Web/HTML/Element/meta.

**Comment by edwardhorsford** [comment]
It's currently 146 characters in. Would have to be a pretty large message (though ascii art...) to push it 512 bytes out.

But - does introduce a risk if used badly. Thoughts?

**Comment by fofr** [comment]
I'd prefer not to introduce a new variable for this bespoke need.

When using the prototype it will need to be started by a developer from somewhere – that might also be a good place to put a warning message.

**Comment by edwardhorsford** [comment]
I'm not sure it is a bespoke need - though I admit I'm possibly the first to request it. Placing a generic message in the top of the source is something I've certainly seen across other websites.

In this particular case it's also useful that *we* can identify whether service is built on the kit or not. Putting something out on the server doesn't help.

If we avoid adding easy insertion points to the kit (I think we should have many more), services end up hacking the template and make upgrading harder.

**Comment by robinwhittleton** [comment]
We’ve got a `top_of_page` insertion point that’s before the doctype. Would obviously have the same concerns about pushing the charset declaration outside the 512 byte limit, but it’s usable now.

(Aside: putting a comment before the doctype used to trigger quirks mode in IE. This behaviour was [fixed in IE10](https://developer.mozilla.org/es/docs/Quirks_Mode_and_Standards_Mode#How_does_Mozilla_determine_which_mode_to_use.3F). Do people regularly test their prototypes in IE9 or lower?)

**Comment by nickcolley** [comment]
Maybe we could `console.info` (once)?

```js
if (
  window.localStorage && window.localStorage.getItem('prototypeWarning') !== 'true' &&
  window.console && window.console.info
) {
  window.console.info('GOV.UK Prototype Kit - do not use this kit for production services');
  window.localStorage.setItem('prototypeWarning', true);
}
```

![screen shot 2016-08-17 at 10 22 00](https://cloud.githubusercontent.com/assets/2445413/17731255/773391c2-6464-11e6-8561-601441005ddf.png)

**Comment by edwardhorsford** [comment]
@nickcolley I think that's a nice addition regardless. I'd be tempted to show it on *every* page load though, not just the first.

**Comment by edwardhorsford** [comment]
@nickcolley I'm going to add your solution (minus the one-off bit). However, I still think we should have something in the html. This is because I anticipate teams using the kit for production are more likely to strip out js printed in to the console vs content in the html.

With that said, I think we might be able to close this issue as I think the needs can be served otherwise:
* That users of the kit are warned not to use if for production - can be done via console as @nickcolley 
* That we be able to positively identify if a thing is made with the kit - we can probably hack something in to the html _secretly_ like map makers insert dead end roads to identify forgeries. An `after_doctype`would make this easier.

Longer term I'd still like to see *far* more insertion points, ideally before and after each major element.

**Comment by robinwhittleton** [comment]
Regarding your second point, GOV.UK already does this (e.g. https://www.gov.uk/government/case-studies has `<meta name="govuk:rendering-application" content="whitehall">`).

**Comment by edwardhorsford** [comment]
Does it use one of the insertion blocks to insert that, or something else?

**Comment by robinwhittleton** [comment]
Nope, [slimmer does it](https://github.com/alphagov/slimmer/blob/1c2afc697ff6f67db6d793bf73714a8823a3748f/lib/slimmer/processors/metadata_inserter.rb#L21).

**Comment by edwardhorsford** [comment]
Cool, might try doing something similar. Not entirely sure how I'd get it in though. Presumably I need to interrupt / insert in to the nunjucks render?

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.
