### ISSUE TITLE
NTA font is missing some accented characters

### ISSUE THREAD

**Issue by daveraine** [alphagov/govuk_template#207]
We're having an issue displaying the å character in the "NTA" font. It seems it is missing and so is falling back to Arial to display the letter, which results in it looking out of place.

I've created a [jsfiddle](https://jsfiddle.net/w8620oqq/) recreating the issue.

**Comment by antimega** [comment]
Hi

Do you need this character in services you're developing, or for GOV.UK content? There are different ways to solve this (some characters were removed from the font to keep the file size as small as possible).

thanks
Chris.

**Comment by daveraine** [comment]
Yes, I am developing the [International Waste Shipments](https://github.com/EnvironmentAgency/prsd-iws) service. We display a lot of foreign towns and competent authorities in the system. The å character is the first one we've noticed is missing, but there could be others. Do you have a list of all the characters that are in the web font? I could cross check this with our data.

**Comment by antimega** [comment]
Hi

I do - can you email me - chris.heathcote at digital.cabinet-office.gov.uk - and we'll find a way to get you the extra glyphs. I suspect if you're working on an international service there are more that you will need.

thanks
Chris.
