### ISSUE TITLE
For Consideration: Gov.UK logo conflicting with service name on tablet breakpoint

### ISSUE THREAD

**Issue by mrbootle-moj** [alphagov/govuk_template#210]
I raised this issue on the cross designers email group.

While testing the MoJ service Help with Fees on an iPad we are using for on site testing I noticed that the break point for tablet portrait meant the service name was underneath the Gov.UK logo. The space between the items seems 'tighter' than on mobile and I ended up tapping the incorrect link (see image below).

It made me question why the service name was underneath the logo given there was ample space.

I understand that if the service name is long this might be a better solution but it did make me question  whether others have experienced this same problem (accidentally tapped the incorrect link.)

![gov uk help with fees links clash](https://cloud.githubusercontent.com/assets/17982645/14921862/47850cc8-0e2c-11e6-8c7a-5294dafdd031.jpg)

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.

This issue has been [captured on GOV.UK Frontend here](https://github.com/alphagov/govuk-frontend/issues/972).
