### ISSUE TITLE
The collection of auto generated examples is missing default text

### ISSUE THREAD

**Issue by gemmaleigh** [alphagov/govuk_template#211]
If I preview the GOV.UK template here:
http://alphagov.github.io/govuk_template/

There are default values which appear to be missing.

For this preview version, it would be helpful if these were provided.
1. In the header, the text "GOV.UK" should appear next to the crown.
2. The OGL text should appear next to the OGL logo. "All content is available under the Open Government Licence v3.0, except where otherwise stated."
3. "© Crown copyright" is missing from under the Crown logo in the footer

There may well be other values which are also missing that aren't immediately visible, the cookie message and the text in the "skip to main content" link.

cc. @alphagov/team-patterns-and-tools

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.
