### ISSUE TITLE
Chrome `font-size-adjust` bug can break footer CSS

### ISSUE THREAD

**Issue by tombye** [alphagov/govuk_template#220]
We position the `.footer-meta-inner` and `.copyright` columns in the `.footer-meta` div as inline elements (`inline-block` in fact) to vertically align them to the base of their parent. We also use the [remove whitespace between inline elements](https://davidwalsh.name/remove-whitespace-inline-block) hack to ensure that between them the columns fill the space of their container.

![footer_columns](https://cloud.githubusercontent.com/assets/87140/16015313/014d4b1a-318d-11e6-9517-a36b11c28f08.png)

If you apply one of the [NTA typography mixins](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/_typography.scss) to `.footer-meta` or any element further up the DOM (ie `body`), this causes the calculation of horizontal space in `.footer-meta` to break in Chrome:

![image](https://cloud.githubusercontent.com/assets/87140/16015337/1d95a7e0-318d-11e6-9946-e731825e1aeb.png)

A simplified example can be seen here:

https://jsbin.com/puzarakubu/1/edit?css,output

I've found resetting `font-size-adjust` at this level fixes it:

https://jsbin.com/finususote/edit?css,output
## Effect of bug

This doesn't effect any apps in the GOVUK stack as none of them set their type at this level but we've seen it on the Digital Marketplace project where we do so on the `<body>` tag.

See our fix for details: https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/338

I've raised it as a [bug on Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=619078).

I think it's debatable this needs fixing at the template level but figured it was worth raising an issue to have it recorded.

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.
