### ISSUE TITLE
Update html5shiv to latest version

### ISSUE THREAD

**Issue by maxf** [alphagov/govuk_template#222]
The included version of html5shiv doesn't support the <dialog> tag. Replacing with the latest version (3.7.3) would fix that.

**Comment by gemmaleigh** [comment]
Hi Max, it looks like the tag you included got stripped out. Was it the `<picture>` element?

#223 fixes this.

**Comment by maxf** [comment]
No, it was the `<dialog>` element :) 
Thanks for the fix.
