### ISSUE TITLE
print css sets link base url to 

### ISSUE THREAD

**Issue by maxf** [alphagov/govuk_template#224]
https://github.com/alphagov/govuk_template/blob/master/source/assets/stylesheets/_core-print.scss#L24
```
a[href^="/"]:after {
  content: " (https://www.gov.uk" attr(href) ")";
  font-size: 90%;
}
```
This breaks if the site isn't on the www.gov.uk domain. (eg *.service.gov.uk).

**Comment by robinwhittleton** [comment]
For GOV.UK we could move this over to [static’s print stylesheet](https://github.com/alphagov/static/blob/master/app/assets/stylesheets/helpers/_core-print.scss). That’d leave relative links on services written out as relative when printed unless the developer chooses to add their own override (unlikely I guess). Better than what’s currently happening though.

**Comment by robinwhittleton** [comment]
[PR #823](https://github.com/alphagov/static/pull/823) adds the gov.uk link prefix to static’s print stylesheet. Once that’s merged I’ll remove it from template.
