### ISSUE TITLE
Propositional navigation .menu button feels buggy

### ISSUE THREAD

**Issue by feedmypixel** [alphagov/govuk_template#229]
# .menu button

The `.menu` button shown in `mobile` view in [example-proposition-menu](http://alphagov.github.io/govuk_template/example-proposition-menu.html) feels a little buggy.
- Menu button disappears when clicked
- Menu button shows when JavaScript is off
### Current

In `mobile` view with `JavaScript` on when you click the `.menu` button it disappears via the `.js-hidden` helper
### Expected

The `.menu` button shouldn't hide when you click it
### Example

![menu-govuk-template](https://cloud.githubusercontent.com/assets/2305016/16488742/e6edceee-3ec9-11e6-9399-bec8bcd8aecb.gif)

---
### Current

In `mobile` view with `JavaScript` off the `.menu` element is still visible
### Expected

`.menu` has no functionality with `JavaScript` off so it should only be show when `JavaScript` is on
### Example

![menu-govuk-template-js-off](https://cloud.githubusercontent.com/assets/2305016/16488737/e2dd61de-3ec9-11e6-810a-f8b9285988e4.gif)

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.

We believe that we have addressed these issues in the [GOV.UK Design System](https://design-system.service.gov.uk/components/header/).
