### ISSUE TITLE
npm releases of govuk_template aren't up to date

### ISSUE THREAD

**Issue by dsingleton** [alphagov/govuk_template#230]
`npm` packages aren't being updated when we release a new version, due to some incorrect config in our CI server (which does the publishing).

The `npm` credentials were rotated and although they were updated in CI deployment config, this hasn't fully deployed to the CI, so the publish tasks are still using the old auth and failing.

GOVUK Infrastructure are investigating why the crediants aren't updating, but in the mean time no new releases of `govuk_template` are being pushed to `npm`, and once it's fixed we may need to do some cleanup to ensure any missed releases are published.

**Comment by robinwhittleton** [comment]
This was resolved early last week.
