### ISSUE TITLE
Font loading strategy

### ISSUE THREAD

**Issue by Guntrisoft** [alphagov/govuk_template#236]
Hi,

I'm working on Pension Wise and was recently doing some web page performance testing.

I noticed that the site was slow to first paint due downloading the font css file, which is blocking rendering.

<img width="590" alt="screen shot 2016-08-11 at 11 35 27" src="https://cloud.githubusercontent.com/assets/6049076/17586168/dc9de640-5fb7-11e6-87ec-fb682ac67eb4.png">

Has there been any discussion in getting this changed so the font loading is non-blocking?

**Comment by nickcolley** [comment]
Hey @Guntrisoft !

We've been tracking this over at https://trello.com/c/V6cfAMpY/3-webfonts-are-huge-and-blocking

Generally we want to try and reduce the impact as much as possible without showing a fallback font, so the work currently is to reduce the payload size.

However we'll also be investigating a non-blocking approach if that's not as fruitful as we'd like.

 Also feel free to contact me directly if you'd like to know more about what's going on :) I'm on the cross government chat if that's easy, or email is cool 👍

**Comment by Guntrisoft** [comment]
@nickcolley thanks for that info nick!

**Comment by 36degrees** [comment]
Hi @Guntrisoft,

I appreciate it's been a long time since you raised this, but just to let you know that I believe this was fixed in #341, and so I'm going to close this issue now. Thanks for raising!
