### ISSUE TITLE
Integrate SRI for scripts / stylesheets

### ISSUE THREAD

**Issue by robinwhittleton** [alphagov/govuk_template#238]
The [Subresource Integrity specification](https://www.w3.org/TR/SRI/) adds a new `integrity` attribute to `<script>` and `<link>` elements that is a hash of the asset they point to. Browsers that support SRI can then hash the downloaded asset and check that it matches the hash specified in the integrity attribute. We [recently implemented this](https://github.com/alphagov/verify-frontend/pull/192) on [verify-frontend](https://github.com/alphagov/verify-frontend/) for the application specific files but we’d like to turn it on for the govuk_template styles and scripts as well.

On verify-frontend it was as simple as using [sprockets-rails](https://github.com/rails/sprockets-rails) `integrity` attribute passed into `javascript_include_tag` and `stylesheet_link_tag` but as we compile govuk_template into multiple different template languages we can’t do that here. To implement this we’ll have to hash [govuk-template.js](https://github.com/alphagov/govuk_template/blob/master/source/assets/javascripts/govuk-template.js) and [govuk-template.scss](https://github.com/alphagov/govuk_template/blob/master/source/assets/stylesheets/govuk-template.scss) post-compilation, and add those hashes manually to an `integrity` attribute on their respective `<script>` and `<link>` tags.

**Comment by robinwhittleton** [comment]
Got a branch that’ll generate integrity hashes for tagged `<link>`s and ’<script>`s and compile them into the template at https://github.com/alphagov/govuk_template/tree/sri . Still to do: fix the tests and add some more around this functionality, and check to make sure that everything is still being packaged correctly.

**Comment by boffbowsh** [comment]
We have a ticket in Core Formats' backlog to look at this https://trello.com/c/58oo6NSQ/481-spike-enable-subresource-integrity-sri-on-our-frontend-apps-1-day

**Comment by robinwhittleton** [comment]
Yeah, that’s for the individual frontend services (or rather, one to start). Hopefully on those it should be trivial, or [at least it was for Verify](https://github.com/alphagov/verify-frontend/pull/192). That only covers the JS/CSS supplied in the individual apps though. To gain full coverage GOV.UK will need to enable SRI in static (again, fairly trivial once you’ve verified that the approach is OK) and to have it in the template which is what this work does. Doing this also means that verify-frontend will have SRI applied to every CS/JSS asset - currently it’s not on the template assets.

**Comment by robinwhittleton** [comment]
OK, a couple of tests are in. I’ll need to actually check this in a live application before I’m happy enough to open a PR, but it’s moving.

**Comment by nickcolley** [comment]
Thanks Robin, I've completed a spike to see what we'd need to do for GOV.UK

https://trello.com/c/58oo6NSQ/481-spike-enable-subresource-integrity-sri-on-our-frontend-apps-1-day

And from that some specific cards for Core to address
https://trello.com/c/zTKJNFiC/693-enable-subresource-integrity-sri-on-government-frontend

**Comment by robinwhittleton** [comment]
Looks like this was fixed in 0.23.0.
