### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by jaherulalom** [alphagov/govuk_template#240]
Im quite new to this. 

I have cloned a copy of this repo using tower and it is tracking the origin/master.

I have opened the project using Aptana Studio 3. 

I have not done any changes at all. Just want to run the app

When i run it opens up on firefox and does not display correctly. 

Im sure i am missing something. Is there a tutorial or documentation i can follow.

**Comment by robinwhittleton** [comment]
Hi Jaherul, thanks for getting in touch.

Primarily govuk_template provides a shared header and footer for GOV.UK and services that run on it. It’s not really designed to run as its own thing; usually people find the version that matches their templating language (for example Mustache or ERB) and pull it into their app as a package (we publish to Rubygems and NPM).

If you want to prototype a GOV.UK service then the [prototype kit](https://github.com/alphagov/govuk_prototype_kit/) will provide a better base for you to work from. This is a Node.JS project that already includes this template along with other components and styles.

Does that explain enough to get started? Happy to answer any more questions you might have.
