### ISSUE TITLE
Sass styles are nested too deeply

### ISSUE THREAD

**Issue by esr360** [alphagov/govuk_template#251]
The compiled CSS results in selectors like the following:

``` css
#footer .footer-meta .footer-meta-inner .open-government-licence .logo {
    ...
}
```

It doesn't really seem as though any CSS naming convention is being used, which for large, production-ready services, should be the case.

I think an entire re-write of the Sass/CSS using a consistent, sensible convention is required at some point, though the implications on the markup could mean that this would be a very big task.

At the very least, I think the current Sass could be re-worked without having to modify the markup.

**Comment by robinwhittleton** [comment]
This stuff is pretty old at this point, and naming conventions weren’t as common then as they are now. We are currently undertaking a [reworking of parts of the frontend code](https://designnotes.blog.gov.uk/2016/09/08/improving-tools-and-resources-for-designers-in-government/) that we produce, and we’re absolutely looking at selectors as part of it. This work will be a break from the old, so it’s an ideal time to establish better conventions.

**Comment by esr360** [comment]
Great news, if you need any help I'd be more than happy to assist with anything at all.
