### ISSUE TITLE
Inline scripts need hashes provided for CSP directives

### ISSUE THREAD

**Issue by robinwhittleton** [alphagov/govuk_template#258]
We supply two inline scripts inside the standard template. Projects (specifically Verify) would like to whitelist these in their CSPs so that they can disable other inline scripts. To do this they’ll need hashes for them.

For the mean time I’ve advised Verify to hardcode the hashes as they rarely change. I’ve also advised them that if we change them in the near future that’d constitute a breaking change and we’d bump the major version number.

Longer term, it’d be good to produce (as part of the package) a list of hashes for the inline scripts in this project. A simple solution would be to drop this into a hardcoded JSON file in the project. A better solution would be to pull the inline scripts out to separate files, which would allow the build process to both generate the hashes and insert them inline (potentially minifying them in the process). Thanks to @nickcolley for that idea.

**Comment by JoeChapman** [comment]
Alternatively to hashes we could use nonces, the difference being that nonces are generated on each request by the app's middleware, so they are dynamic and there is no need to store a collection of hashes.
The nonce is generated in middleware and assigned to `res.locals`, and the `script-src` directive the CSP middleware. The `res.locals` value can be picked up in the template so long as the script tag has a placeholder attribute.

E.g. 
```
<script nonce=${nonce}></script>
```

**Comment by JoeChapman** [comment]
PR will add a placeholder to the script tags for a nonce https://github.com/alphagov/govuk_template/pull/268

**Comment by JoeChapman** [comment]
@robinwhittleton 

> A better solution would be to pull the inline scripts out to separate files, which would allow the build process to both generate the hashes and insert them inline (potentially minifying them in the process). 

If the inline scripts were pulled out to js files, hashes wouldn't be needed. The js files could be served from the service domain and therefore meet the `script-src`: ["'self'"]` directive

**Comment by fofr** [comment]
Putting the "is js enabled" script (https://github.com/alphagov/govuk_template/blob/master/source/views/layouts/govuk_template.html.erb#L33) in a separate file would be a performance hit. It needs to run before content displays and this would slow down time to first paint. cc @nickcolley

**Comment by nickcolley** [comment]
Yeah, we'd block the page on an additional request that is not guaranteed to respond quickly, unacceptable for our users so we'd need another approach.

**Comment by JoeChapman** [comment]
@fofr, @nickcolley I agree, it is not always ideal for js to be externalised. My point was that if it was, then it wouldn't need a hash or a nonce.

**Comment by nickcolley** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches.

I've reviewed the closed pull request, and it seems as though for this issue it can be better solved by using hashes.

That said, we want to ensure we are not blockers for security so if you think that this is indeed a required feature to enable CSP for your project please re-open.
