### ISSUE TITLE
Focused links have low contrast

### ISSUE THREAD

**Issue by cfq** [alphagov/govuk_template#264]
Links don't have good contrast against $focus-colour when they're in focus, it's currently 4.07:1. Keyboard users who have low vision would notice them. Screen magnification and keyboard users whose zoom follow keyboard focus would find it hard if they need high contrast.

We can fix it by setting the link colour on focus to be the same as $text-colour.

Current:
<img width="343" alt="screen shot 2016-12-07 at 15 27 17" src="https://cloud.githubusercontent.com/assets/9111/20977162/8a8a53ec-bc9c-11e6-992f-3bbcfae9b41c.png">

Proposed:
<img width="356" alt="screen shot 2016-12-07 at 15 26 11" src="https://cloud.githubusercontent.com/assets/9111/20977168/931c55be-bc9c-11e6-83d6-d8849caca9ea.png">

**Comment by edwardhorsford** [comment]
Since it's very close to being acceptable, I wonder if we could just go with a slightly darker version of link colour? The black looks rather different, whereas a darker blue isn't _that_ noticeable.

Example:
![screen shot 2016-12-07 at 17 15 52](https://cloud.githubusercontent.com/assets/2204224/20978477/ef358948-bca0-11e6-94a9-c03e7688e77d.png)

**Comment by quis** [comment]
The blue and orange isn’t a good colour combination because of [chromostereopsis](https://en.wikipedia.org/wiki/Chromostereopsis).

**Comment by robinwhittleton** [comment]
I don’t mind the black, but it does cause another problem: it’s impossible to tell whether the currently focused link has been visited.

**Comment by edwardhorsford** [comment]
@trevorsaint has pointed out that the contrast is poor on our service names when focused.

Example:
![unnamed](https://cloud.githubusercontent.com/assets/2204224/22423262/b43af914-e6e8-11e6-87ac-e884903d0380.png)

Suggest the solution here is to make the service name black when focused - it then matches the proposition links that are already black.
