### ISSUE TITLE
Skip link is hardcoded to point at #content

### ISSUE THREAD

**Issue by quis** [alphagov/govuk_template#271]
GOV.UK Template hardcodes the skiplink to point at `#content` (see [this line](https://github.com/alphagov/govuk_template/blob/master/source/views/layouts/govuk_template.html.erb#L39)). But GOV.UK Elements adds styles to `#content` (see [this block](https://github.com/alphagov/govuk_elements/blob/d6226bd2c8c7e256f995c0f519daaa4035c6bd54/public/sass/elements/_layout.scss#L9-L20)).

There are cases where we don’t want the thing we identify as `#content` to have those styles.

Would it be possible to override where the skiplink points to, so we could have `<a href="#anything-else" class="skiplink">`?

**Comment by gemmaleigh** [comment]
Alternatively, we could set GOV.UK elements to use a class instead, for example, `.main-content`, that would allow id="content" to be reserved for the target of the skiplink.

**Comment by quis** [comment]
@gemmaleigh Yes. Although that would be more of a breaking change for users of Elements I think.

**Comment by gemmaleigh** [comment]
It would! I was going to add that. Sorry, this is something from GOV.UK elements that you're having to work around.

**Comment by quis** [comment]
No problem, I don’t think it’s a use case you could’ve reasonably foreseen.

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.

We've [captured this issue on GOV.UK Frontend here](https://github.com/alphagov/govuk-frontend/issues/971).
