### ISSUE TITLE
gouk_template demo site has inconsistent header positioning

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_template#273]
The vertical position of the service name looks off on the demo site. Unsure if this is the demo site or an issue with template itself. The name is too high.

![screen shot 2017-01-30 at 13 13 38](https://cloud.githubusercontent.com/assets/2204224/22424363/3d1822ca-e6ee-11e6-8b9b-ff520c201cda.png)

I note also that links move vertically between [this page](http://alphagov.github.io/govuk_template/example-proposition-menu.html) and [this page](http://alphagov.github.io/govuk_template/example-proposition-link.html) - which feels like a bug.

**Comment by andymantell** [comment]
Just encountered this myself. It looks like the correct alignment is achieved by wrapping it in `<nav id="proposition-menu">`

But it does feel like maybe it should align correctly without that.

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.
