### ISSUE TITLE
Add support for theme-color?

### ISSUE THREAD

**Issue by willp-bl** [alphagov/govuk_template#277]
It would be nice to be able to have [theme-color](https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android) set so the browser window matches the site.  Robin and I tested this in the verify-frontend by adding `<meta name="theme-color" content="#0b0c0c" />`

That only works for Android.  iOS did not seem to have a similar option and we had not tested Windows Mobile.

Can this be added to govuk_template?

**Comment by nickcolley** [comment]
Yeah this makes sense!

If you want to make a PR and need some help let us know. :)
