### ISSUE TITLE
Add ruby and sass linting

### ISSUE THREAD

**Issue by fofr** [alphagov/govuk_template#280]
The template has no linting.

* source directory needs sass linting
* build_tools, Gemfiles and lib should be ruby linted

I've started in this branch:
https://github.com/alphagov/govuk_template/tree/lint

* Linting requires a sass gem upgrade which needs a sprockets bump
* The fonts.css file can't easily be excluded from the linter

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.
