### ISSUE TITLE
Release 0.20.0 isn't recorded as a release

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk_template#296]
Release 0.20.0 is not showing up in [the list of releases on GitHub](https://github.com/alphagov/govuk_template/releases) despite having been [merged](https://github.com/alphagov/govuk_template/commit/af97d0d61ccccdb7f61410e5e383c3130269c9e1) and [pushed downstream](https://rubygems.org/gems/govuk_template/versions/0.20.0).

I believe this is most likely related to the move from Jenkins to Travis.

**Comment by fofr** [comment]
Same is true for https://github.com/alphagov/govuk_template/pull/302 and https://github.com/alphagov/govuk_template/pull/303

**Comment by fofr** [comment]
Seeing failures when PRs are merged:
https://github.com/alphagov/govuk_template/commits/master

**Comment by h-lame** [comment]
I think #297 is an attempt to fix the problems on travis that mean we don't tag things anymore.

**Comment by 36degrees** [comment]
We've manually been through and released all the missing versions. There's still a bit of work to do to make Travis do this automatically.
