### ISSUE TITLE
Public fonts vs secret fonts

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_template#298]
We have our EOT publically here but the WOFFs are hidden? https://github.com/alphagov/govuk_template/tree/master/source/assets/stylesheets/fonts

**Comment by fofr** [comment]
When I tried adding linting it wasn't easy to exclude the fonts.css file from the linter: https://github.com/alphagov/govuk_template/issues/280

**Comment by nickcolley** [comment]
No longer an issue
