### ISSUE TITLE
Consider removing link ink skipping

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_template#313]
In #281 we added `text-decoration-skip: ink;` to skip underlines near descenders - in theory because it looks better.

I wonder if we should reconsider this decision.

There are many examples where it makes single links look like multiple links. Are we happy with this? 

NB - it generally looks better in Safari which doesn't skip as much.

Discuss.

## Chrome

![screen shot 2017-05-05 at 11 37 38](https://cloud.githubusercontent.com/assets/319055/25742411/45c34f4c-3187-11e7-965c-86bf82ee1a72.png)
![screen shot 2017-05-05 at 11 37 32](https://cloud.githubusercontent.com/assets/319055/25742412/45c7f880-3187-11e7-9781-db70ac70cfe7.png)
![screen shot 2017-05-05 at 11 40 08](https://cloud.githubusercontent.com/assets/319055/25742496/a61a8a5e-3187-11e7-8272-01426d469ba0.png)

## Safari

![screen shot 2017-05-05 at 11 38 15](https://cloud.githubusercontent.com/assets/319055/25742434/58eade64-3187-11e7-9eba-13c6bb722730.png)
![screen shot 2017-05-05 at 11 38 11](https://cloud.githubusercontent.com/assets/319055/25742436/58ee3f32-3187-11e7-932a-0b484e4c5c76.png)

**Comment by selfthinker** [comment]
I would be in favour of reverting it again. Evidence from a single user: It actually has happened to me that I opened the same page twice because I didn't realise that it was the same link.

**Comment by soniaturcotte** [comment]
Agree. 

Additionally, there are also instances within single words where the letter combinations just look strange. 
<img width="422" alt="screen shot 2017-06-08 at 16 19 09" src="https://user-images.githubusercontent.com/19776089/26938960-b6296e0a-4c6d-11e7-8ecd-fb57db53e0fa.png">

**Comment by alextea** [comment]
To the contrary in 4 rounds of research on GOV.UK since this was deployed we haven't seen any issues with people getting confused.

**Comment by edwardhorsford** [comment]
I wonder if we might be able to test anything in analytics related to this - any ideas?

Perhaps: number of people opening the _same_ link twice from one source page - ie clicking both parts because they thought they were two links.

**Comment by alextea** [comment]
Will discuss with Vin when he is back from leave as we are already measuring this stuff for navigation. Not sure if we will have any significant findings however.

**Comment by selfthinker** [comment]
On the other hand, have there ever been users in user research who said anything ever about underlining? ;-)

**Comment by nickcolley** [comment]
Just to clarify the original change was to make links (in lists) more legible.

I'd be 👍  to revert since Chrome doesnt seem to render these as well as Safari 😢

**Comment by fofr** [comment]
@alextea I think it's less about getting confused and more about cognitive load and readability.
I'm in favour of reverting until Chrome has better typography.

As discussed with @nickcolley, words containing `g` and `p` appear easier to read, while other characters like `y`, commas `,` and brackets `)` leave strange artefacts that look like punctuation or a break in the text. I think the latter is more damaging than the former is beneficial – but that's opinion and reckons.

**Comment by alextea** [comment]
@selfthinker it's not about what they say, but we have observed that in some circumstances users don't recognise text as links when it is not underlined.

**Comment by alextea** [comment]
I'm also in favour of reverting btw.

**Comment by 36degrees** [comment]
To be clear, are we considering actively disabling it in Safari (where it's on by default) or are we just talking about removing the 'opt in' for Chrome?

**Comment by edwardhorsford** [comment]
I think Safari is marginally better. Don't know if it's good enough to keep though.

Chrome:
![screen shot 2017-06-13 at 10 21 53](https://user-images.githubusercontent.com/2204224/27075505-4c335d54-5022-11e7-936b-059ec7b4f9c2.png)

Safari:
![screen shot 2017-06-13 at 10 23 50](https://user-images.githubusercontent.com/2204224/27075561-7188a9ba-5022-11e7-8a21-94dfad6f12f2.png)

**Comment by nickcolley** [comment]
In safari that is the default behaviour, not something we introduced just fyi

**Comment by gemmaleigh** [comment]
Fixed by #316.

**Comment by robinwhittleton** [comment]
Did anyone file a bug with Chrome about this issue? Would be good to reinstate in future if they fix their rendering.
