### ISSUE TITLE
Focused, unvisited links are (extremely) low-contrast

### ISSUE THREAD

**Issue by alex-ju** [alphagov/govuk_template#325]
An attempt to fix #264 raised this issue of having blue text on green buttons when focused on unvisited links.
<img width="240" alt="screen shot 2017-09-15 at 14 21 40" src="https://user-images.githubusercontent.com/788096/30484549-9d794026-9a22-11e7-8df8-5544539296b5.png">
<img width="241" alt="screen shot 2017-09-15 at 14 21 53" src="https://user-images.githubusercontent.com/788096/30484548-9d71dda4-9a22-11e7-8345-6bb8105c4061.png">

Tested with latest Chrome, Firefox on OSX and Windows and IE9, IE10, IE11 on Windows.

If we do want to [make focused links slightly darker to improve contrast](https://github.com/alphagov/govuk_template/commit/79466a489c38b0b82f4cb95daa2baba41b375a81), I would get rid of `:link` (which selects unvisited links). So the code below
`a:link:focus { color: darken( $link-colour, 2.5%) }`
would become
`a:focus { color: darken( $link-colour, 2.5%) }`
or even simpler, I would move the color attribution inside `a:focus`, which is [a few lines above](https://github.com/alphagov/govuk_template/commit/79466a489c38b0b82f4cb95daa2baba41b375a81#diff-d0d347595f17783ceb1cfde3086eee86R58).

In this way we will have a "less powerful" selector (for improving contrast on links) that won't affect buttons.

If that sounds good, let me know and I'll come up with a PR.

**Comment by nickcolley** [comment]
cc @edwardhorsford

**Comment by edwardhorsford** [comment]
The button text should *always* be white. It's a mistake that it's blue.

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.
