### ISSUE TITLE
Favicon missing 48x48 size

### ISSUE THREAD

**Issue by timja** [alphagov/govuk_template#328]
The favicon currently has 16x16 and 32x32 resolutions.
Microsoft recommends including at least a 48x48 one as well.
Android would also use this for high definition.
https://msdn.microsoft.com/library/gg491740(v=vs.85).aspx

A scan of gov.uk:
https://realfavicongenerator.net/favicon_checker?protocol=https&site=www.gov.uk

Easiest way to generate a new one given the right image:
https://realfavicongenerator.net/

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, which wouldn't include addressing this, so I'm going to close this.

However, it still seems to be an issue in GOV.UK Frontend, so I've [raised an issue there to track this](https://github.com/alphagov/govuk-frontend/issues/963).

Thanks for raising, and sorry that it's taken so long to reply.
