### ISSUE TITLE
Is the font copyright notice correct?

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_template#335]
The [copyright notice embedded with the font](https://github.com/alphagov/govuk_template/blob/630dae63bb43db12c1d60838c016f0a25cc7f717/source/assets/stylesheets/fonts.css#L3) starts with "Copyright (c) 2011 by Margaret Calvert & Henrik Kubel."

I wonder if this is correct. Are Margaret Calvert and Henrik Kubel the copyright holders, or is A2 Type? The font license I've seen mentions A2/SW/HK Limited.

**Comment by Nooshu** [comment]
Hey Ed,
After speaking to Mark H he agreed that we should follow what is listed int he font metadata. See below:
<img width="709" alt="font-info" src="https://user-images.githubusercontent.com/1223960/37213495-1a420f32-23aa-11e8-828f-af412274a29c.png">
