### ISSUE TITLE
Things are still being hidden with a non-clip method

### ISSUE THREAD

**Issue by philsherry** [alphagov/govuk_template#336]
There are references to an older method for visually hiding things off the screen. We switched to using the `clip` method a while back, so these should be investigated and brought into line. 

`.ir { text-indent: -999em; }`

`.visually-hidden, .visuallyhidden { left: -9999em; }`

`.skiplink { left: -9999em; }`

All of these things are happening in this file: 

`govuk_template/source/assets/stylesheets/_accessibility.scss`

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.
