### ISSUE TITLE
For discussion: disable link ink skipping.

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_template#339]
Back in 2017 we enabled link skipping (#281 ). After some discussion (#313 ) we then disabled it (#316).

Links skipping has now been enabled by default in some browsers so I wonder if we should explicitly disable it.

I think the same reasons apply to making it default disabled as existed last year: while it may look prettier, it often makes a single link look like multiple links - particularly when near punctuation. The skip is often far larger than necessary. Until browser vendors release an improved implementation, we should disable.

[By way of dropbox paper](https://paper.dropbox.com/doc/Links-xiWNcJk5Wpb8Sj6G4Prtl), we've also had this accessibility comment from the Digital Accessibility Center:

> We have recently had a suggestion from the Digital Accessibility Centre that links, where the underline is broken by descending letters, are not good for users of assistive technology.  In particular, a ZoomText user viewing a link at high magnification would have trouble identifying where the link ends.

**Comment by nickcolley** [comment]
Could we consider raising this with browser vendors? As suggested by Robin here? https://github.com/alphagov/govuk_template/issues/313#issuecomment-311927325

**Comment by edwardhorsford** [comment]
#Current browser behavior on Mac:

## Chrome:
![ink-skipping-chrome](https://user-images.githubusercontent.com/2204224/36743740-ebeeee08-1be2-11e8-98fc-9b88dff4839b.png)

## Safari
![ink-skipping-safari](https://user-images.githubusercontent.com/2204224/36743762-f4ada0a2-1be2-11e8-986d-57bfab8ba210.png)

## Firefox
![screen shot 2018-02-27 at 17 21 03](https://user-images.githubusercontent.com/2204224/36743768-fa2b8b0c-1be2-11e8-88b1-453d22412767.png)

And with `text-decoration-skip-ink: none;` applied:

## Chrome
![ink-skip-chrome-disabled](https://user-images.githubusercontent.com/2204224/36743949-76b1f418-1be3-11e8-80bd-54697e881d4b.png)


## Safari
Didn't seem to work.

**Comment by nickcolley** [comment]
@edwardhorsford safari may be using https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip

**Comment by robinwhittleton** [comment]
Safari (or at least the current version on my 10.13 laptop) still needs `-webkit-text-decoration-skip-ink: none`.

**Comment by pflannery** [comment]
Yeah I think disabling ink makes sense. 

This is an org name i just saw in an integration test so thought I would share

![image](https://user-images.githubusercontent.com/1727302/36936219-1cbf4cde-1efa-11e8-8945-3c84ea20eb09.png)

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.

We've [captured this issue on GOV.UK Frontend here](https://github.com/alphagov/govuk-frontend/issues/973).
