### ISSUE TITLE
Download links are broken on github page.

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_template#360]
If you try to download govuk_template from a download link on http://alphagov.github.io/govuk_template/ it'll result in a 404

**Comment by nickcolley** [comment]
Potentially this change has stopped releases from being put into downloads:
https://github.com/alphagov/govuk_template/commit/f2fdfaa0ea75c227c0e7374a2b94f9d3e8d83030

**Comment by nickcolley** [comment]
This looks to be the code that is responsible for getting the releases into downloads: https://github.com/alphagov/govuk_template/blob/master/build_tools/publisher/release_publisher.rb#L16

**Comment by nickcolley** [comment]
Could also be a change in dependency with ockokit: https://github.com/alphagov/govuk_template/commit/f1b143738e571122d1e2a31a518ac38d725c5ecf#diff-abbc50ed35eba6863b02c76535084ae3R29

**Comment by nickcolley** [comment]
Struggling to see the output of the deployments since I'm not sure if they have stored logs in the same way that builds do.

https://docs.travis-ci.com/user/deployment/script/

This means I can't check the result of https://github.com/alphagov/govuk_template/blob/master/.travis.yml#L19

**Comment by igloosi** [comment]
i have manually added some tars for the 0.0.24 release

**Comment by nickcolley** [comment]
If this is an issue in the future I will re-open.
