### ISSUE TITLE
Include footer links in the template

### ISSUE THREAD

**Issue by alexmuller** [alphagov/govuk_template#40]
The Performance Platform makes use of govuk_template, but we're hosted on www.gov.uk - so having the footer links available would be really useful for us. We're a special case technically, of course.

[For now we've included the HTML and CSS](https://github.com/alphagov/spotlight/pull/29) because we need to be consistent across multiple frontend apps while we're transitioning to our own infrastructure, but as @bradleywright notes that doesn't work long-term.

Does anybody have any thoughts on making the GOV.UK footer links available in this project?

**Comment by dsingleton** [comment]
I'm doing a general clean up of old and/or state issues, so closing this.

We've lived with this for going on 3 years and quite a few people involved aren't working on the projects anymore.
