### ISSUE TITLE
Setting far-future cache headers on assets

### ISSUE THREAD

**Issue by alexmuller** [alphagov/govuk_template#44]
Hi,

I'd like to set far-future cache headers on my assets subdomain.

However, the template [doesn't look like it's flexible enough](https://github.com/alphagov/govuk_template_mustache/blob/v0.3.7/views/layouts/govuk_template.html#L42) to allow me to do this:

```
<link rel="shortcut icon" href="{{ assetPath }}images/favicon.ico" type="image/x-icon" />
```

I'm planning to use [grunt-digest](https://npmjs.org/package/grunt-digest) to generate assets of the form `favicon-12820cc3033bdd51838998f4bf538f4c.ico`, similar to the way in which the Rails asset pipeline works.

Does anyone have any suggestions, or is this an enhancement that could be made to the template?

Thanks,

Alex

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.
