### ISSUE TITLE
print css hides all footer elements

### ISSUE THREAD

**Issue by Demotive** [alphagov/govuk_template#64]
```
/* hide the unnecessary page elements */
body footer,
.visuallyhidden,
#global-cookie-message,
#skiplink-container {
  display: none !important;
}
```

https://github.com/alphagov/govuk_template/blob/master/source/assets/stylesheets/_core-print.scss#L66

Perhaps `body > footer` or `#footer` would be less hardcore?

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.
