### ISSUE TITLE
Cachebusting is causing us pain

### ISSUE THREAD

**Issue by harry-m** [alphagov/govuk_template#67]
Hello,

We're finding that the cachebusting query strings are causing older browsers not to cache the assets. Here's the guilty commit:

https://github.com/alphagov/govuk_template/commit/68a35d69bb02b727bd2ab1162c6a05d6dbe46022

Any chance this could be removed, or the version number incorporated into the filenames? If not, can we make the cachebusting configurable when the templates are built? We'd rather have none at all than to have them in querystrings.

Open to other solutions if anyone knows of something that'll cause bad browsers to play ball.

Harry

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.
