### ISSUE TITLE
Add styles for search boxes in the header

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk_template#77]
Services that have search boxes in the header (like the Service Manual) currently have had to create the styles for those boxes from scratch.

How about we add those styles to the template? This is what we've done for the proposition header and navigation styles after all.

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, which wouldn't include addressing this, so I'm going to close this.

We don't have a component for the search box, but it is [in our backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/132).
