### ISSUE TITLE
Images are messily organised

### ISSUE THREAD

**Issue by alextea** [alphagov/govuk_template#87]
When compiled, there are images in 3 places in the `/app` folder.
- `/app/assets/images`
- `/app/assets/stylesheets`
- `/app/assets/stylesheets/images`

(The `external-link` images do not appear in the `/source/assets/stylesheets` folder.)

Should these be tidied up?

**Comment by matthewford** [comment]
It's an issue with loading assets in new versions of rails, all assets need to be assed manually to be precompiled.

**Comment by rusllonrails** [comment]
In Rails 4.2.5.1 it causes:
```
Add `Rails.application.config.assets.precompile += %w( apple-touch-icon-152x152.png )` to `config/initializers/assets.rb` and restart your server
```

Solution is to set assets manually:
```
Rails.application.config.assets.precompile += %w(
  apple-touch-icon-152x152.png
  apple-touch-icon-120x120.png
  apple-touch-icon-76x76.png
  apple-touch-icon-60x60.png
  opengraph-image.png
  open-government-licence.png
  open-government-licence_2x.png
  govuk-crest.png
  govuk-crest-2x.png
  govuk-crest-ie.png
  gov.uk_logotype_crown.png
  gov.uk_logotype_crown-1x.png
  gov.uk_logotype_crown_invert_trans.png
  file.png
)
```

**Comment by timpaul** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Template will now only get major bug fixes and security patches, so I'm going to close this.
