### ISSUE TITLE
Tarball build fails on Windows

### ISSUE THREAD

**Issue by lukeferguson** [alphagov/govuk_template#88]
When attempting to build the tarball in a Windows environment, the following error is produced:

    C:\IR\rails_apps\govuk_template>bundle exec rake build:tar
    Compiling assets and templates into ./app
    rake aborted!
    Errno::ENOENT: No such file or directory - cp -r --parents layouts/govuk_template.html.erb C:/IR/rai
    ls_apps/govuk_template/app/views
    C:/IR/rails_apps/govuk_template/build_tools/compiler/asset_compiler.rb:81:in `block in copy_views'
    C:/IR/rails_apps/govuk_template/build_tools/compiler/asset_compiler.rb:71:in `chdir'
    C:/IR/rails_apps/govuk_template/build_tools/compiler/asset_compiler.rb:71:in `copy_views'
    C:/IR/rails_apps/govuk_template/build_tools/compiler/asset_compiler.rb:29:in `compile'
    C:/IR/rails_apps/govuk_template/build_tools/compiler/asset_compiler.rb:13:in `compile'
    C:/IR/rails_apps/govuk_template/Rakefile:10:in `block in <top (required)>'
    Tasks: TOP => build:tar => compile
    (See full trace by running task with --trace)

Any ideas?

**Comment by dsingleton** [comment]
Hi,

I'm clearing up older & stale issues. I'm closing this for now, as I can't replicate.

If you can, please let us know we'll look into it.

Thanks!
