### ISSUE TITLE
gov.uk in header has weird onclick style in firefox

### ISSUE THREAD

**Issue by alxndrsn** [alphagov/govuk_template#98]
When gov.uk text and crown in the header is "active" (e.g. while holding mouse button down), the following behaviour is observed:
# Chrome & Safari
- crown stays white
- "GOV.UK" turns blue
- underline turns blue
# Firefox
- crown stays white
- "GOV.UK" turns blue
- underline turns blue
- text background goes yellow
- yellow box appears around crown and text
# Conclusion

Firefox looks weird; should it look like Chrome/Safari?

**Comment by robinwhittleton** [comment]
Thanks for the report @alxndrsn , I’ve noticed this too and I’ll bump it up my list.

**Comment by robinwhittleton** [comment]
This doesn’t seem to be an issue any more: the active state is the same as the focused state. Not sure which commit actually fixed it, but @selfthinker did some work around the header for better accessibility a while back which might have helped.
